apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    shared-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend-development
  labels:
    shared-gateway-access: "true"
