apiVersion: v1
kind: Secret
metadata:
  name: backend-go-secrets
type: Opaque
stringData:
  APP_DB_URL: "postgres://user:pass@localhost:5432/db"
  APP_DB_PASSWORD: "dummy"
  APP_JWT_SECRET: "dummy-jwt-secret"
  APP_SECRET_KEY: "dummy-secret-key"
  APP_NEWRELIC_KEY: "dummy-nr-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-go-pem-secrets
type: Opaque
stringData:
  banking_private_key.pem: "dummy-pem-content"
